---
 - hosts: hadoopv1
   tasks:
    - name: Starting namenode
      shell: '/usr/bin/hadoop/hadoop-daemon.sh start namenode'
 - hosts: tasktracker
   tasks:
    - name: Starting datanode
      shell: '/usr/bin/hadoop/hadoop-daemon.sh start datanode'

