---
 - hosts: hadoopv1
   tasks:
    - name: Starting namenode
      shell: '/etc/hadoop/sbin/hadoop-daemon.sh start namenode'
    - name: Starting jobtracker
      shell: '/etc/hadoop/sbin/hadoop-daemon.sh start jobtracker'
 - hosts: tasktracker
   tasks:
    - name: Starting datanode
      shell: '/etc/hadoop/sbin/hadoop-daemon.sh start datanode'
    - name: Starting tasktracker
      shell: '/etc/hadoop/sbin/hadoop-daemon.sh start tasktracker'

